- name: feature
  color: "0e8a16"
  description: "New feature or enhancement"

- name: bug
  color: "d73a4a"
  description: "Something isn't working"

- name: documentation
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: frontend
  color: "fbca04"
  description: "Frontend-related work"

- name: backend
  color: "5319e7"
  description: "Backend-related work"

- name: auth
  color: "1d76db"
  description: "Authentication-related feature"

- name: notes
  color: "5319e7"
  description: "Note functionality"

- name: search
  color: "f9d0c4"
  description: "Search-related feature"

- name: UI/UX
  color: "c2e0c6"
  description: "User interface or experience improvement"

- name: AI
  color: "ff99cc"
  description: "Artificial intelligence or ML integration"

- name: good first issue
  color: "7057ff"
  description: "Easy to pick up for new contributors"

- name: "difficulty: easy"
  color: "bfe5bf"
  description: "Small, simple change or fix"

- name: "difficulty: medium"
  color: "fef2c0"
  description: "Moderately challenging"

- name: "difficulty: hard"
  color: "f9d0c4"
  description: "Complex or time-intensive task"